//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class testEntities : DbContext
    {
        public testEntities()
            : base("name=testEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Drzava> Drzava { get; set; }
        public virtual DbSet<Grad> Grad { get; set; }
        public virtual DbSet<RequestLog> RequestLog { get; set; }
    
        public virtual ObjectResult<DohvatiDrzaveIGradovePoBrojuStanovnika_Result> DohvatiDrzaveIGradovePoBrojuStanovnika(Nullable<int> brojStanovnika)
        {
            var brojStanovnikaParameter = brojStanovnika.HasValue ?
                new ObjectParameter("BrojStanovnika", brojStanovnika) :
                new ObjectParameter("BrojStanovnika", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DohvatiDrzaveIGradovePoBrojuStanovnika_Result>("DohvatiDrzaveIGradovePoBrojuStanovnika", brojStanovnikaParameter);
        }
    
        public virtual ObjectResult<DohvatiGradovePoDrzavi_Result> DohvatiGradovePoDrzavi(Nullable<int> drzavaID)
        {
            var drzavaIDParameter = drzavaID.HasValue ?
                new ObjectParameter("DrzavaID", drzavaID) :
                new ObjectParameter("DrzavaID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DohvatiGradovePoDrzavi_Result>("DohvatiGradovePoDrzavi", drzavaIDParameter);
        }
    }
}
